DROP TABLE IF EXISTS `gbase_tables`;
CREATE TABLE `gbase_tables` (
  `TABLE_CATALOG` VARCHAR(512) DEFAULT NULL,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_TYPE` VARCHAR(64) NOT NULL DEFAULT '',
  `ENGINE` VARCHAR(64) DEFAULT NULL,
  `VERSION` BIGINT(21) UNSIGNED DEFAULT NULL,
  `ROW_FORMAT` VARCHAR(10) DEFAULT NULL,
  `TABLE_ROWS` BIGINT(21) UNSIGNED DEFAULT NULL,
  `AVG_ROW_LENGTH` BIGINT(21) UNSIGNED DEFAULT NULL,
  `DATA_LENGTH` BIGINT(21) UNSIGNED DEFAULT NULL,
  `MAX_DATA_LENGTH` BIGINT(21) UNSIGNED DEFAULT NULL,
  `INDEX_LENGTH` BIGINT(21) UNSIGNED DEFAULT NULL,
  `DATA_FREE` BIGINT(21) UNSIGNED DEFAULT NULL,
  `AUTO_INCREMENT` BIGINT(21) UNSIGNED DEFAULT NULL,
  `CREATE_TIME` DATETIME DEFAULT NULL,
  `UPDATE_TIME` DATETIME DEFAULT NULL,
  `CHECK_TIME` DATETIME DEFAULT NULL,
  `TABLE_COLLATION` VARCHAR(32) DEFAULT NULL,
  `CHECKSUM` BIGINT(21) UNSIGNED DEFAULT NULL,
  `CREATE_OPTIONS` VARCHAR(255) DEFAULT NULL,
  `TABLE_LIMIT_STORAGE_SIZE` BIGINT(21) UNSIGNED DEFAULT NULL,
  `TABLE_STORAGE_SIZE` BIGINT(21) UNSIGNED DEFAULT NULL,
  `TABLE_DATA_SIZE` BIGINT(21) UNSIGNED DEFAULT NULL,
  `TABLE_COMMENT` VARCHAR(2000) NOT NULL DEFAULT '',
  `LOCAL_HASH_INDEX_FILE_SIZE` BIGINT(21) UNSIGNED DEFAULT NULL,
  `GLOBAL_HASH_INDEX_FILE_SIZE` BIGINT(21) UNSIGNED DEFAULT NULL,
  `SCN` BIGINT(21) UNSIGNED DEFAULT NULL,
  `TABLE_ID` BIGINT(21) UNSIGNED DEFAULT NULL,
  `OWNER_UID` BIGINT(20) NOT NULL DEFAULT '0',
KEY idx_db_tbl (TABLE_SCHEMA,TABLE_NAME)
)
ENGINE=FEDERATED CONNECTION='server_gbase_inforschema/tables' DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `gbase_columns`;
CREATE TABLE `gbase_columns` (
  `TABLE_CATALOG` varchar(512) DEFAULT NULL,
  `TABLE_SCHEMA` varchar(64) NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) NOT NULL DEFAULT '',
  `COLUMN_NAME` varchar(64) NOT NULL DEFAULT '',
  `ORDINAL_POSITION` bigint(21) unsigned NOT NULL DEFAULT '0',
  `COLUMN_DEFAULT` longtext,
  `IS_NULLABLE` varchar(3) NOT NULL DEFAULT '',
  `DATA_TYPE` varchar(64) NOT NULL DEFAULT '',
  `CHARACTER_MAXIMUM_LENGTH` bigint(21) unsigned DEFAULT NULL,
  `CHARACTER_OCTET_LENGTH` bigint(21) unsigned DEFAULT NULL,
  `NUMERIC_PRECISION` bigint(21) unsigned DEFAULT NULL,
  `NUMERIC_SCALE` bigint(21) unsigned DEFAULT NULL,
  `CHARACTER_SET_NAME` varchar(32) DEFAULT NULL,
  `COLLATION_NAME` varchar(32) DEFAULT NULL,
  `COLUMN_TYPE` longtext NOT NULL,
  `COLUMN_KEY` varchar(3) NOT NULL DEFAULT '',
  `EXTRA` varchar(27) NOT NULL DEFAULT '',
  `PRIVILEGES` varchar(80) NOT NULL DEFAULT '',
  `COLUMN_COMMENT` varchar(2000) NOT NULL DEFAULT '',
KEY idx_db_tbl_col (TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME)
)
ENGINE=FEDERATED CONNECTION='server_gbase_inforschema/columns' DEFAULT CHARSET=utf8mb4;

